import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import { WEBSITE_TITLE_DIVISOR, WEBSITE_TITLE } from '@/constants';
import './_styles/index.css';

const robotoFont = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
  weight: 'variable',
  display: 'swap',
});

export const metadata: Metadata = {
  title: {
    template: `%s ${WEBSITE_TITLE_DIVISOR} ${WEBSITE_TITLE}`,
    default: WEBSITE_TITLE,
  },
  description: 'Generated by create next app',
  icons: [
    {
      url: '/app_icons/192x192.png',
      sizes: '192x192',
      type: 'image/png',
      rel: 'icon',
    },
    {
      url: '/app_icons/96x96.png',
      sizes: '96x96',
      type: 'image/png',
      rel: 'icon',
    },
    {
      url: '/app_icons/180x180.png',
      sizes: '180x180',
      type: 'image/png',
      rel: 'apple-touch-icon',
    },
    {
      url: '/app_icons/32x32.png',
      sizes: '32x32',
      type: 'image/png',
      rel: 'icon',
    },
  ],
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="en" className={`${robotoFont.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
